version: '2'
services:
    patientportal-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/PatientPortal/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=PatientPortal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
